#!/usr/bin/env bash
# ============================================================================
# setup-utils.sh — bootstrap the third RQ4 component: utils (data layer).
#
# Run from the RQ4 repo root:
#     bash scripts/setup-utils.sh
#
# What this does:
#   1. Write ./utils/.env with the tu-zi gateway credentials. Used by
#      utils/classify/run.py and pipeline.py.
#   2. Create the Python venv at agent/.venv (reused from components 1 & 2
#      if present) and install openai>=1.0 there.
#   3. Run a smoke test: download a SMALL subset of the dataset (3 dirs)
#      and classify one issue end-to-end to prove the LLM path works.
#
# Idempotent.
#
# Big-picture: utils has three sub-components:
#     utils/download/  - sparse-checkout AgentBug-Smith
#     utils/classify/  - LLM-classify each issue → data/index.jsonl
#     utils/split/     - stratified, repo-disjoint train/test split
# Run all three: `python utils/pipeline.py` after this setup.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

UTILS_ENV="$REPO_ROOT/utils/.env"
UTILS_ENV_EXAMPLE="$REPO_ROOT/utils/.env.example"
VENV="$REPO_ROOT/agent/.venv"
SMOKE_DIR="$REPO_ROOT/utils/smoke"
SMOKE_SCRIPT="$SMOKE_DIR/run_smoke.sh"
PIPELINE_SMOKE="$REPO_ROOT/utils/pipeline_smoke.py"

TUZI_API_KEY="${TUZI_API_KEY:-sk-52RaA81V3pImnAGLRby5kMbDWVVDcXkZkmBPXlj4D7pUxLvv}"
TUZI_BASE_URL="${TUZI_BASE_URL:-https://api.tu-zi.com/v1}"
DEFAULT_MODEL="${DEFAULT_MODEL:-gpt-4.1-mini}"

log()  { printf '\033[1;34m[setup-utils]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[setup-utils][warn]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[setup-utils][error]\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

# ---------------------------------------------------------------------------
# 1. .env
# ---------------------------------------------------------------------------
mkdir -p "$REPO_ROOT/utils"

if [[ -f "$UTILS_ENV" ]]; then
    log "Reusing $UTILS_ENV"
else
    cat > "$UTILS_ENV" <<EOF
# Generated by scripts/setup-utils.sh — consumed by utils/classify/run.py
# and utils/pipeline.py. Source it before running: source utils/.env.
TUZI_API_KEY=$TUZI_API_KEY
TUZI_BASE_URL=$TUZI_BASE_URL
DEFAULT_MODEL=$DEFAULT_MODEL
EOF
    chmod 600 "$UTILS_ENV"
    log "Wrote $UTILS_ENV (mode 600)"
fi

cat > "$UTILS_ENV_EXAMPLE" <<'EOF'
# Copy to .env (mode 600) and re-run setup-utils.sh.
TUZI_API_KEY=sk-replace-me
TUZI_BASE_URL=https://api.tu-zi.com/v1
DEFAULT_MODEL=openai/gpt-4o-mini
EOF
log "Wrote $UTILS_ENV_EXAMPLE"

# Make sure utils/.env is gitignored.
GITIGNORE="$REPO_ROOT/.gitignore"
touch "$GITIGNORE"
grep -qxF 'utils/.env' "$GITIGNORE" || echo 'utils/.env' >> "$GITIGNORE"
grep -qxF 'data/' "$GITIGNORE" || echo 'data/' >> "$GITIGNORE"
log "Updated .gitignore (utils/.env, data/)"

# ---------------------------------------------------------------------------
# 2. venv + openai
# ---------------------------------------------------------------------------
if [[ ! -d "$VENV" ]]; then
    log "Creating Python venv at $VENV"
    python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"

log "Installing openai>=1.0 ..."
pip install --quiet --upgrade 'openai>=1.0'

# ---------------------------------------------------------------------------
# 3. Smoke test — sparse-checkout 3 dirs, classify 1 issue
# ---------------------------------------------------------------------------
mkdir -p "$SMOKE_DIR"

cat > "$SMOKE_SCRIPT" <<'BASH'
#!/usr/bin/env bash
# Smoke test: prove the full data path works end-to-end on a small slice.
#   1. Sparse-checkout exactly 3 issue directories (--filter=blob:none +
#      a single-path sparse-checkout).
#   2. Classify them via the LLM gateway.
#   3. Verify the index has 3 records and at least 1 has a valid category.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# shellcheck disable=SC1091
source utils/.env

SMOKE_RAW="$REPO_ROOT/utils/smoke/raw"
SMOKE_INDEX="$REPO_ROOT/utils/smoke/index.jsonl"
rm -rf "$SMOKE_RAW" "$SMOKE_INDEX"

# Pick 3 dirs by listing the remote once.
TMP_LIST="$(mktemp -t agentbug-list.XXXXXX)"
git ls-remote --heads https://github.com/EaminC/AgentBug-Smith.git HEAD >/dev/null 2>&1 || true
# Listing contents needs the API; fall back to cloning metadata only.
git clone --depth 1 --filter=blob:none --sparse \
    https://github.com/EaminC/AgentBug-Smith.git "$SMOKE_RAW/.probe" 2>/dev/null
cd "$SMOKE_RAW/.probe"
git sparse-checkout set results/all_combined_f2p
PICK3=$(ls results/all_combined_f2p | head -3)
echo "[smoke] picked dirs: $PICK3"
cd "$REPO_ROOT"
rm -rf "$SMOKE_RAW"

# Re-do the sparse-checkout, this time with only those 3 dirs in the spec.
mkdir -p "$SMOKE_RAW"
SMOKE_WORK="$SMOKE_RAW/.probe"
git clone --depth 1 --filter=blob:none --sparse \
    https://github.com/EaminC/AgentBug-Smith.git "$SMOKE_WORK" 2>&1 | tail -2
cd "$SMOKE_WORK"
{
    for d in $PICK3; do
        echo "results/all_combined_f2p/$d"
    done
} > .git/info/sparse-checkout
git checkout HEAD 2>&1 | tail -2

# Move the 3 dirs into place.
mkdir -p "$SMOKE_RAW/results/all_combined_f2p"
mv results/all_combined_f2p/* "$SMOKE_RAW/results/all_combined_f2p/"
cd "$REPO_ROOT"
rm -rf "$SMOKE_WORK"

# Classify.
python utils/classify/run.py \
    --in "$SMOKE_RAW/results/all_combined_f2p" \
    --out "$SMOKE_INDEX" \
    --model "${DEFAULT_MODEL:-gpt-4.1-mini}" \
    --base-url "${TUZI_BASE_URL:-https://api.tu-zi.com/v1}" \
    --api-key "${TUZI_API_KEY:?}" \
    --concurrency 4

# Verify.
N=$(wc -l < "$SMOKE_INDEX" | tr -d ' ')
if [[ "$N" != "3" ]]; then
    echo "[smoke] FAIL: expected 3 records, got $N" >&2
    exit 1
fi
GOOD=$(grep -E '"category": "[A-F]"' "$SMOKE_INDEX" | wc -l | tr -d ' ')
if [[ "$GOOD" -lt 1 ]]; then
    echo "[smoke] FAIL: no record has a valid A-F category" >&2
    cat "$SMOKE_INDEX" >&2
    exit 1
fi
echo "[smoke] OK: 3 classified, $GOOD have valid A-F categories"
echo "SMOKE_OK"
BASH
chmod +x "$SMOKE_SCRIPT"
log "Wrote $SMOKE_SCRIPT"

log "Running smoke test (3-issue classification round-trip)..."
set +e
SMOKE_OUTPUT="$(bash "$SMOKE_SCRIPT" 2>&1)"
SMOKE_RC=$?
set -e

echo "$SMOKE_OUTPUT"
if (( SMOKE_RC != 0 )) || ! grep -q '^SMOKE_OK$' <<<"$SMOKE_OUTPUT"; then
    die "Smoke test failed — see output above."
fi

log "✅ Setup complete."
log ""
log "Next steps:"
log "  source agent/.venv/bin/activate"
log "  source utils/.env"
log "  python utils/pipeline.py                       # full dataset"
log "  python utils/pipeline.py --limit 20            # 20-issue dry run"
log ""
log "Or step-by-step:"
log "  python utils/download/run.py --out data/raw"
log "  python utils/classify/run.py --in data/raw/results/all_combined_f2p --out data/index.jsonl"
log "  python utils/split/run.py --index data/index.jsonl --train-size 40 --out data/splits/default"