#!/usr/bin/env bash
# ============================================================================
# setup-openhands.sh — bootstrap the second RQ4 component: OpenHands CLI.
#
# Run from the RQ4 repo root:
#     bash scripts/setup-openhands.sh
#
# What this does, in order:
#   1. Verify `openhands` is on PATH (installed via OpenHands' official
#      binary installer script — we do not manage it ourselves).
#   2. Write ./agent/openhands-config/.env with the tu-zi gateway
#      credentials (LLM_API_KEY / LLM_BASE_URL / LLM_MODEL). These are
#      picked up by the wrapper via --override-with-envs.
#   3. Drop a wrapper script (agent/run_openhands.sh) and a config README.
#   4. Run a smoke test that issues a tiny headless task and verifies the
#      artifact file was actually created (proves end-to-end wiring of
#      the CLI ↔ tu-zi gateway ↔ sandbox).
#
# Idempotent: re-running reuses the existing .env in place.
#
# Install (one-time, separate from this script):
#     curl -fsSL https://install.openhands.dev/install.sh | sh
#
# Analogous to scripts/setup.sh (component 1), but the install lives
# outside this repo because the binary ships self-contained.
# ============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

CONFIG_DIR="$REPO_ROOT/agent/openhands-config"
ENV_FILE="$CONFIG_DIR/.env"
ENV_EXAMPLE="$CONFIG_DIR/.env.example"
README_FILE="$CONFIG_DIR/README.md"
RUNNER="$REPO_ROOT/agent/run_openhands.sh"
SMOKE="$CONFIG_DIR/smoke_test.sh"

# ---------------------------------------------------------------------------
# tu-zi gateway configuration (shared with component 1)
# ---------------------------------------------------------------------------
TUZI_API_KEY="${TUZI_API_KEY:-sk-52RaA81V3pImnAGLRby5kMbDWVVDcXkZkmBPXlj4D7pUxLvv}"
TUZI_BASE_URL="${TUZI_BASE_URL:-https://api.tu-zi.com/v1}"
DEFAULT_MODEL="${DEFAULT_MODEL:-openai/gpt-4o-mini}"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log()  { printf '\033[1;34m[setup-oh]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[setup-oh][warn]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[setup-oh][error]\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

# ---------------------------------------------------------------------------
# 1. Verify openhands CLI is on PATH
# ---------------------------------------------------------------------------
need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1 — install it and re-run."
}

if ! need_cmd openhands; then
    die "Install OpenHands CLI with: curl -fsSL https://install.openhands.dev/install.sh | sh"
fi

OH_VERSION="$(openhands --version 2>/dev/null | grep -E '^OpenHands' | head -1 || openhands --version 2>&1 | head -1)"
log "Found openhands: $(command -v openhands) ($OH_VERSION)"

# ---------------------------------------------------------------------------
# 2. Write .env — tu-zi credentials for --override-with-envs
# ---------------------------------------------------------------------------
mkdir -p "$CONFIG_DIR"

if [[ -f "$ENV_FILE" ]]; then
    log "Reusing existing $ENV_FILE"
else
    log "Creating $ENV_FILE with tu-zi gateway credentials"
fi

cat > "$ENV_FILE" <<EOF
# Generated by RQ4 scripts/setup-openhands.sh — credentials consumed by
# agent/run_openhands.sh (sources this file then execs openhands with
# --override-with-envs).
LLM_API_KEY=$TUZI_API_KEY
LLM_BASE_URL=$TUZI_BASE_URL
LLM_MODEL=$DEFAULT_MODEL
EOF
chmod 600 "$ENV_FILE"
log "Wrote $ENV_FILE (mode 600)"

cat > "$ENV_EXAMPLE" <<'EOF'
# Copy to .env and re-run setup-openhands.sh.
# These three vars are required by `openhands --override-with-envs`.
LLM_API_KEY=sk-replace-me
LLM_BASE_URL=https://api.tu-zi.com/v1
LLM_MODEL=openai/gpt-4o-mini
EOF
log "Wrote $ENV_EXAMPLE"

# ---------------------------------------------------------------------------
# 3. README — what this component is and how to use it
# ---------------------------------------------------------------------------
cat > "$README_FILE" <<EOF
# Component 2 — OpenHands CLI

Upstream: <https://github.com/OpenHands/OpenHands-CLI>
Installed via (separate, one-time): \`curl -fsSL https://install.openhands.dev/install.sh | sh\`
API gateway: <https://api.tu-zi.com> (OpenAI-compatible)

## Why CLI, not Agent Canvas

The npm-based [\`@openhands/agent-canvas\`](https://www.npmjs.com/package/@openhands/agent-canvas)
spins up a web UI on port 8000. That's GUI. We want the same one-shot
shape as component 1 (CLI takes a task, makes the changes, exits). The
official \`OpenHands-CLI\` binary has a headless mode that matches.

## Boundary

| Layer | Owner | Tracked? |
| --- | --- | --- |
| \`openhands\` binary (\`~/.local/bin/openhands\`) | OpenHands installer | **No** (system-level) |
| \`config/\`, \`run_openhands.sh\` | **RQ4** | Yes |

## Files

- \`run_openhands.sh\` (parent dir) — sources \`.env\`, then runs
  \`openhands --headless --override-with-envs --yolo "\$@"\`.
- \`.env\` — \`LLM_API_KEY\` / \`LLM_BASE_URL\` / \`LLM_MODEL\`. Gitignored, \`chmod 600\`.
- \`.env.example\` — template.
- \`smoke_test.sh\` — issues a tiny task, verifies the artifact.

## Usage

\`\`\`bash
# one-time bootstrap (assuming the binary is already installed)
bash scripts/setup-openhands.sh

# run a task — same shape as component 1
bash agent/run_openhands.sh -t "fix the failing test in src/foo.py"
\`\`\`

> \`--yolo\` is auto-appended by the wrapper. Headless mode already
> always auto-approves actions, so this is just defensive.
EOF
log "Wrote $README_FILE"

# ---------------------------------------------------------------------------
# 4. Wrapper — single command to run a task
# ---------------------------------------------------------------------------
cat > "$RUNNER" <<EOF
#!/usr/bin/env bash
# run_openhands.sh — invoke the OpenHands CLI headless with our env loaded.
# Usage: bash agent/run_openhands.sh -t "your task"   (or pass any openhands flags)
set -euo pipefail
REPO_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
set -a
source "$ENV_FILE"
set +a
exec openhands --headless --override-with-envs --yolo "\$@"
EOF
chmod +x "$RUNNER"
log "Wrote $RUNNER"

# ---------------------------------------------------------------------------
# 5. Smoke test — actual end-to-end task run
# ---------------------------------------------------------------------------
cat > "$SMOKE" <<'BASH'
#!/usr/bin/env bash
# Smoke test for the OpenHands CLI: issues a tiny task and verifies that
# the agent actually produced the requested artifact. This exercises:
#   - wrapper / .env loading
#   - --override-with-envs flowing LLM_API_KEY / LLM_BASE_URL / LLM_MODEL
#     into the CLI
#   - the tu-zi gateway responding
#   - the agent's tool-execution sandbox (writing files to a tmp dir)
set -euo pipefail

WORK_DIR="$(mktemp -d /tmp/rq4-oh-smoke.XXXXXX)"
EXPECTED_FILE="$WORK_DIR/smoke.txt"
EXPECTED_CONTENT="rq4-component2-smoke"
LOG_FILE="$WORK_DIR/trajectory.log"

cleanup() {
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

echo "[smoke] work dir:    $WORK_DIR"
echo "[smoke] expected:     $EXPECTED_FILE"
echo "[smoke] trajectory:   $LOG_FILE"

cd "$WORK_DIR"
# Issue a simple task the agent can complete in one turn.
# Headless mode already auto-approves, but --yolo is defensive.
openhands --headless --override-with-envs --yolo \
    --exit-without-confirmation \
    --json \
    -t "Create a file at $EXPECTED_FILE containing exactly the text '$EXPECTED_CONTENT' (no other characters, no trailing newline). Just write the file and stop — do not run any other commands." \
    >"$LOG_FILE" 2>&1

if [[ ! -f "$EXPECTED_FILE" ]]; then
    echo "[smoke] FAIL: $EXPECTED_FILE was not created." >&2
    echo "[smoke] trajectory (tail):" >&2
    tail -n 60 "$LOG_FILE" >&2 || true
    exit 1
fi

ACTUAL_CONTENT="$(cat "$EXPECTED_FILE")"
if [[ "$ACTUAL_CONTENT" != "$EXPECTED_CONTENT" ]]; then
    echo "[smoke] FAIL: expected '$EXPECTED_CONTENT', got '$ACTUAL_CONTENT'" >&2
    tail -n 60 "$LOG_FILE" >&2 || true
    exit 1
fi

echo "[smoke] OK: $EXPECTED_FILE contains the requested text"
echo "SMOKE_OK"
BASH
chmod +x "$SMOKE"
log "Wrote $SMOKE"

# ---------------------------------------------------------------------------
# 6. Run smoke test
# ---------------------------------------------------------------------------
log "Running smoke test (issues a tiny headless task via --override-with-envs)"
set +e
SMOKE_OUTPUT="$(bash "$SMOKE" 2>&1)"
SMOKE_RC=$?
set -e

echo "$SMOKE_OUTPUT"
if (( SMOKE_RC != 0 )) || ! grep -q '^SMOKE_OK$' <<<"$SMOKE_OUTPUT"; then
    die "Smoke test failed — see output above."
fi

log "✅ Setup complete."
log ""
log "Next steps:"
log "  bash agent/run_openhands.sh -t \"<your task>\"    # run a task (headless, auto-approve)"
log ""
log "Files of interest:"
log "  • env loader   $ENV_FILE  (source it for custom runs)"
log "  • config docs  $README_FILE"
log "  • wrapper      $RUNNER"
log "  • smoke test   $SMOKE"
log "  • upstream     openhands CLI  ($(command -v openhands))"